### ISSUE TITLE
Incompatibility with Simplepie

### ISSUE THREAD

**Issue by markpea** [djplaner/moodle-mod_bim#14]
I have Simplepie RSS system installed in Moodle 1.9.7 instead of Magpie. BIM creates a nasty error when running cron.php:

> Server Time: Fri, 30 Apr 2010 16:14:33 +0000
> Starting activity modules
> Processing module function assignment_cron ...done.
> Processing module function chat_cron ...done.
> Processing module function forum_cron ...Starting digest processing...
> Cleaned old digest records
> done.
> Processing module function forumng_cron ...
> Email processing:
> I>nitial query: 0s
> Marking processed posts: 0s.
> Email processing (0 new posts) complete, total: 0s
> Beginning forum deleted/edit message cleanup...
> Message search: 0s
> No old deleted / edited messages to clean up.
> done.
> Processing module function bim_cron ...done.
> Finished activity modules
> Starting blocks
>     Processing cron function for rss_client....<br />
>     <b>Fatal error</b>:  Cannot redeclare class SimplePie_Cache_MySQL in 
>     <b>/usr/home/markp/public_html/clamp-LAE/lib/simplepie_1.2/simplepie.inc</b> on line  <b>9069</b><br />

This also occurs if I try to use an RSS feed in the same course as a BIM activity.

**Comment by djplaner** [comment]
Mark,

BIM comes with its own copy of Simplepie.  Like you I saw the problems around Magpie and BIM really needs to build on a firm foundation of feed manipulation and Simplepie was the best solution.

The complicating factor is that Simplepie doesn't appear to be standard with Moodle, so I had to include it in BIM.  Which causes a clash if you have it installed.

The solution would probably be to remove BIM's simplpie.  I can't do this (yet) with the main source as too many Moodle installs don't have it.

Some instructions
- remove BIM's simplepie
  Delete the directory/folder  ~/moodle/mod/bim/lib/simplepie 
  This is where BIM's simplepie resides
- update the require in ~/moodle/mod/bim/lib/bim_rss.php
  This is the only file that uses simplepie.  Line 17 of this file is
      require_once($CFG->dirroot.'/mod/bim/lib/simplepie/simplepie.inc');
  You need to change this to point to your version of Simplepie (or perhaps you don't need to given the clash you're getting).

Hope this helps.

David.

**Comment by markpea** [comment]
Removing BIM's simplepie and linking to the other location did correct the problem generated by cron.php --  see http://www.earlham.edu/markp/millmiss/index.html#%5b%5bBIM%20problems%20:%20more%5d%5d 
But now I don't get any marking action -- http://www.earlham.edu/markp/millmiss/index.html#%5b%5bBIM%20problems%20%3A%20process%20issues%5d%5d

**Comment by markpea** [comment]
Marking action sorted -- egregious user error!
