### ISSUE TITLE
Big BIM icon

### ISSUE THREAD

**Issue by ghost** [djplaner/moodle-mod_bim#18]
David, I'm not sure if it's just our imlementation, but just in case others have this too, the icon in our Site Menu block is 64x63 instead of the usual 16x16, as is the one at the top of the "update this BIM" page.  I can send you a couple of screenshots if you like.  - Alan

**Comment by djplaner** [comment]
Thanks for reminding me Alan about this problem.  Yep, it is the size of the file.  I've updated the github source with a smaller version.

**Comment by ghost** [comment]
yikes - that was fast! now, back to that PhD  :-)

**Comment by djplaner** [comment]
:) Make sure you check that it worked.  Fast might be a sign of sloppy work.

As for PhD, Ha.   Have an ALTC application to think about.
