### ISSUE TITLE
Open links to student blogs in new window

### ISSUE THREAD

**Issue by djplaner** [djplaner/moodle-mod_bim#2]
Requests from CQU staff for the links to the students' blogs and posts on their blog to open in a new window.

I have a prejudice against applications that open a new window, if I want a new window I'll "right click" on the link and use the option in the menu.

However, if I get votes for this it will be done - quite simple

**Comment by ghost** [comment]
how about allowing the teacher to make the choice with a config option? i prefer new windows for links that go off-site, not otherwise - obviously others have different prefs and you'll never pick a winner :)

**Comment by djplaner** [comment]
:) I agree with the idea of user choice, I just interpret as the user being able to choose to use right click.

Adding a config option is a good idea, though it is more work and given my prejudice and workload, not something I'm liable to do soon.  However, if someone else wanted to make the change..

One problem is that at the moment, the only person who configures BIM is the coordinator. The individual teacher doesn't get a config option.  So, at the moment it would be coordinator choice.

I wonder if Moodle has a global config option for this?

**Comment by markpea** [comment]
My 2c is with you David. I think it's a mistake to override what should be an end  user operation.

**Comment by ghost** [comment]
My perspective is as a mac laptop trackpad user, for whom the equivalent of right-click is a two handed operation, and if i'm required to do this for my each of my students' blog posts, I'm likely to get grumpy more quickly than usual. Select once, use many times is not a bad enduser-focussed design principal.  Moodle does have an option like this to open resources in same/new window but i'm not sure if the use is consistent across other areas (imho it would be better to make this a profile setting )   We're quite often asked to change the dafault from whatever it is at the time :) I'll ask NetSpot to take a look at how big a task it might be to give coordinators &/or markers this option.

**Comment by djplaner** [comment]
Alan, catching up on some BIM stuff.  I take the point about mac laptop folk and not necessarily being nice (though a mac laptop is all I use :) ).

I've seen the Moodle wide option in some places.  If there is a Moodle wide approach to this, I'm happy to modify BIM to work with this.  After all BIM is meant to be integrated with Moodle.    I'm reluctant to do this as a BIM specific thing, but can see the point.

The other complicating factor, is that this particular change might have to wait in line.

**Comment by ghost** [comment]
+1 for not making this a BIM-specific thing.  imho better to put something in the tracker to improve this personalisation through, say the profile.  definitely not a big issue for us though - its about 393rd in the priority list at the moment ;)

**Comment by djplaner** [comment]
Closing this out given my prejudice and feedback from others.
