### ISSUE TITLE
Issues with UTF8 characters

### ISSUE THREAD

**Issue by tlock** [djplaner/moodle-mod_bim#22]
This byte string was making the adodb logger to fail and bim marking to fail on find student :-

'A' (65)
's' (115)
's' (115)
'i' (105)
'g' (103)
'n' (110)
'm' (109)
'e' (101)
'n' (110)
't' (116)
's' (115)
'�' (226)
'�' (128)
'�' (153)

function bim_clean_content( $content ) {
-        chr(153),

**Comment by djplaner** [comment]
Sorry Tim.  I'm struggling to understand this one.

As far as I know, bim_clean_content only gets called when processing the RSS, which is before bim marking.  And, I'm not sure what the fix is.

Sorry for being thick.

**Comment by tlock** [comment]
The fix is to replace chr(153) ($badchr) with nothing you have done with other characters like chr(226) and chr(128). Looking back at this I think I need to add an entry for coresponding $goodchr array to replace array key 16 (17th) with ''

**Comment by tlock** [comment]
diff --git a/mod/bim/lib/bim_rss.php b/mod/bim/lib/bim_rss.php
index 078de9c..16113fb 100644
--- a/mod/bim/lib/bim_rss.php
+++ b/mod/bim/lib/bim_rss.php
@@ -424,7 +424,7 @@ function bim_clean_content( $content ) {
     $goodchr    = array(
         '"', '"', "'", "'", "...", "-", "-",
         '\'', '-',
-        ' ', ' ', "'", '', '', '', '', '' );
- ```
     ' ', ' ', "'", '', '', '', '', '', '' );
  ```
  
   $post = str_replace($badchr, $goodchr, $content);

**Comment by djplaner** [comment]
Thanks Tim.  Adding this now.
