### ISSUE TITLE
PostgreSQL issue when marking isn't released and fails because timereleased isn't set

### ISSUE THREAD

**Issue by tlock** [djplaner/moodle-mod_bim#23]
In function bim_marker_mark_post() in marker/view.php

If timerelease was not set it would error doing the update as noted in similar situation in another issue, so the fix is to set it if it isn't set.
-        if (!isset($marking_details[$marking]->timereleased)) {
-            $marking_details[$marking]->timereleased = 0;
-        }
       $safe = addslashes_object( $marking_details[$marking] );

**Comment by djplaner** [comment]
Thanks.  Have made this change.  Will hopefully update github code later today.
