### ISSUE TITLE
Escaping quotes in the Description of a new question

### ISSUE THREAD

**Issue by markpea** [djplaner/moodle-mod_bim#24]
What a student sees when opening Details about this activity : range of questions:
Title   Description
Stream of consciousness Write a \\\\"stream of consciousness\\\\" piece about your life at Earlham.
Progress at Earlham Write a posting about the \\'progressive\\' nature of the Earlham community

Extra escape quotes \ get added to the description text every time a new question is added by the instructor. This could quickly build up to pain-in-the-neck levels :-)

**Comment by djplaner** [comment]
Ahh, yes I did not understand the appropriate use of addslashes.  This has been fixed.
