### ISSUE TITLE
BIM and the Moodle gradebook

### ISSUE THREAD

**Issue by markpea** [djplaner/moodle-mod_bim#25]
I've been digging around in BIM but I still cannot find where to set the overall grade for a BIM activity. This is normally configured in the Settings (Update) page but I don't see an option for setting the max grade there. Looking in Grades : Categories and Items : Full view the max grade seems to be hardcoded at 100. It's not obvious to me how the grades from the questions are accumulated towards this total. It would be nice to have the option that the Forum has in rating posts:
- Average of all question marks (scaled up to maximum). So if 10 questions are marked 10 points each and you choose average, a 9.2 average would be worth 92 marks / 100.
- Sum of question marks. Here the Coordinator would probably want to ensure that the total marks for all the questions = max grade for the BIM assignment.
- Max marks and 
- Min of marks
- Count of questions answered. (I don't know whether this would be of any use)

as well as setting the maximum grade/mark for the BIM activity as a whole.

**Comment by djplaner** [comment]
G'day Mark, 

The minimalist "marking" model currently in BIM is 
- Each question has a minimum and maximum mark (not strictly enforced, just warnings when mark is outside range)
- Marker assigns whatever mark they wish to each student response to a question
- When a marked student response is "released" by the coordinator the mark awarded by the marker is added to the gradebook column for the BIM activity
- If the coordinator wants to scale/modify the overall mark for a BIM activity, they do so in the gradebook

As with much of BIM, this minimalist approach is a function of having to get the initial version done quickly + wanting to make it work as similar as possible to the non-Moodle predecessor to BIM.

That's the explanation/rationale of the current approach, I agree that this is an area that could use some improvement (not a new observation for BIM).

**Comment by djplaner** [comment]
Closing, but making it a part of other issues including #47 #40 and #35
