### ISSUE TITLE
SimplePie, performance and alternatives?

### ISSUE THREAD

**Issue by djplaner** [djplaner/moodle-mod_bim#29]
Appears SimplePie and how it is used in BIM can cause some performance issues on large installations.  There appears to be some value to explore how this can be addressed through either
a) re-working of how SimplePie is used 
b) a replacement for SimplePie

**Comment by tlock** [comment]
Using Magpie is easy, but retrieving only the content within the divs is the tricky part.

$rss = fetch_rss( $url );

echo "Channel Title: " . $rss->channel['title'] . "\n";
foreach ($rss->items as $item) {
  $href = $item['link'];
  $title = $item['title'];
  echo "$href [$title]\n";
}

**Comment by djplaner** [comment]
Seems that Moodle 2.0 is also using SimplePie.  Since this seems to be the trend, will avoid looking for alternatives.
