### ISSUE TITLE
Add support for pass/fail

### ISSUE THREAD

**Issue by djplaner** [djplaner/moodle-mod_bim#3]
Would be good for blog posts to be able to be marked pass/fail

Opens up the question about the use of scales etc.

**Comment by ghost** [comment]
+1 for UC ability to use grade scales  - much better solution than just pass/fail.

**Comment by markpea** [comment]
+1 for grade scales also. Why not make the grading process more like the moodle 'standard'?

**Comment by djplaner** [comment]
For mainly pragmatic and contextual reasons.

Pragmatic because I had to get the first release of BIM done quickly, which meant I didn't have enough time to get to grips with the Moodle 'standard' or how it might work with BIM.

Contextual, because most of the folk who would be using BIM initially at my institution are past BAM (the pre-Moodle version of BIM) users. They are used to the way BAM works.  This term they were making the transition to Moodle for the first time and using BIM for the first time.  I thought it sensible to keep things simple.  So, marking in BIM works exactly as it did in BAM.

**Comment by djplaner** [comment]
Rolling into issue #47 on bim2 and advanced grading.
