### ISSUE TITLE
Changing the allocation of a blog post to 'unallocated' gives an error

### ISSUE THREAD

**Issue by tlock** [djplaner/moodle-mod_bim#31]
To reproduce, go in to marking and use the 'change allocation to' box to allocate the blog post to 'unallocated'. 

This is fixed by changing the question = '' under unallocated to 0 as DB field is an INT in PSQL

--- a/mod/bim/marker/view.php
+++ b/mod/bim/marker/view.php
@@ -245,7 +245,7 @@ function bim_process_allocate_form( $marking_details, $fromform, $questions )/*
 //print "...unallocate..";
             // Change status to unallocated and question to NULL
             $detail->status = "Unallocated";
-            $detail->question = "";
-            $detail->question = 0;
           // update database
  //            if ( ! set_field( 'bim_marking', 'status', $detail->status,
  //                             'question', $detail->question ) )
  @@ -1034,7 +1034,7 @@ function bim_marker_mark_post( $bim, $userid, $cm, $marking )
       if ( $fromform->$menu_name == "Unallocate" )
       {
         $marking_details[$marking]->status = "Unallocated";
-          $marking_details[$marking]->question = "";
-          $marking_details[$marking]->question = 0;
         print_string('bim_mark_unallocated','bim' );
       }
       else // re-allocating to a different question

**Comment by djplaner** [comment]
Thanks Tim.

There was a similar fix last week due to a report from CQU which has now gone to Postgres.  Am about to commit this change now.
