### ISSUE TITLE
PostgreSQL backup issues with lack of table name alias

### ISSUE THREAD

**Issue by tlock** [djplaner/moodle-mod_bim#9]
In functions like :-

backuplib.php: bim_marking_ids_by_course

The SQL table name alias needs to be specified in PSQL :-

```
return get_records_sql(
          "SELECT m.id,m.bim " .
              "FROM {$CFG->prefix}marking m, {$CFG->prefix}bim bim" .
          "WHERE bim.course='$course' AND m.bim=bim.id" );
```

Previously :-

```
return get_records_sql(
          "SELECT m.id,m.bim " .
              "FROM {$CFG->prefix}marking m, {$CFG->prefix}bim " .
          "WHERE bim.course='$course' AND m.bim=bim.id" );
```

**Comment by djplaner** [comment]
Thanks for point this out.  Have fixed this up in the code on github.  It seems to work, but I don't have Postgres so haven't tested there and I've done this in a hurry.

**Comment by tlock** [comment]
This SQL would fail because there is no space after the table alias

"FROM {$CFG->prefix}marking m, {$CFG->prefix}bim bim" .

TO

"FROM {$CFG->prefix}marking m, {$CFG->prefix}bim bim " .

**Comment by tlock** [comment]
my bad...

**Comment by djplaner** [comment]
Ahh, that's what you get when you don't think.  I should've picked up the need for a space.  So much for getting a quick response.  Must take care.

Again, thanks for the feedback.

Wonder if I've introduced another problem?
